### ISSUE TITLE
Security: file access

### ISSUE THREAD

**Issue by fritzw** [arm2arm/files_latexeditor#2]
Depending on the default configuration of the TeX distribution, latex may be able to read any file on the file system, including system configuration files or files other owncloud users.

See: http://tex.stackexchange.com/questions/10418/how-can-i-safely-compile-other-peoples-latex-documents

**Comment by arm2arm** [comment]
Thanks for pointing this, this is very important bug, I am loking a ways to  sandbox latex on serverside.

**Comment by arm2arm** [comment]
what I found that on CentOs 6.4 the default option for write18 is disabled

**Comment by arm2arm** [comment]
Extra   -no-shell-escape is added
