### ISSUE TITLE
owncloud 6 compatability 

### ISSUE THREAD

**Issue by pintjuk** [arm2arm/files_latexeditor#7]
when installing in owncload 6 i get the error:

```
An exception occurred while executing 'INSERT INTO `oc_appconfig` ( `appid`, `configkey`, `configvalue` ) VALUES( ?, ?, ? )': SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'appid' cannot be nul
```

**Comment by domcars0** [comment]
What is the name of the directory containing the plugin? It must be apps/files_latexeditor.
All files in the plugin must be readable by the user running the httpd server (apache or www-data for example).

**Comment by pintjuk** [comment]
yeah, fixed that, the error message is goon and it looks like it is installed. sorry for using you for tech-support but your REDME is kind of thin. Is the text editor a part of this app or is it a dependency?

**Comment by domcars0** [comment]
files_latexeditor need files_texteditor.
If you install files_latexeditor  with OC6 you will probably have to change the 
'owncloud'/lib/private/mimetypes.list.php and Add
'tex' => 'text/x-latex',
'latex' => 'text/x-latex'
At end of the array

Also add
filetype["tex"] = "latex";
in the setSyntaxMode(ext)  function in the files_texteditor/js/editor.js 
if you want .tex extension to be editable.
